name: Dependabot auto-merge

on: pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    uses: crashplangroup/github-workflow-library/.github/workflows/dependabot-automerge.yml@master
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
