name: Go

on:
  push:
    paths-ignore:
        - "docs/**"

env:
  IMAGE_NAME: code42software/axiomatic

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.15.0
      - name: Set up Go Environment Variables
        run: |
          echo "::set-env name=GOPATH::$(dirname $GITHUB_WORKSPACE)"
          echo "::add-path::$(dirname $GITHUB_WORKSPACE)/bin"
        shell: bash
      - name: Check out Source Code
        uses: actions/checkout@v2
      - name: Get dependencies
        run: go mod download
      - name: Format
        run: go fmt .
      - name: Lint
        run: |
          go get -u golang.org/x/lint/golint
          golint -set_exit_status ./...
      - name: Errcheck
        run: |
          go get -u github.com/kisielk/errcheck
          errcheck ./...
      - name: Test
        run: |
          go test ./...
          go test -race ./...
      - name: Measure Coverage
        run: go test -v -covermode=atomic -coverprofile=coverage.out ./...
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.out
