name: Go

on:
  push:
    paths-ignore:
        - "docs/**"

env:
  IMAGE_NAME: code42software/axiomatic

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.15.5
      - name: Check out Source Code
        uses: actions/checkout@v3
      - name: Get dependencies
        run: go mod download
      - name: Format
        run: go fmt .
      - name: Lint
        run: |
          go get -u golang.org/x/lint/golint
          golint -set_exit_status ./...
      - name: Errcheck
        run: |
          go get -u github.com/kisielk/errcheck
          errcheck ./...
      - name: Test
        run: |
          go test ./...
          go test -race ./...
      - name: Measure Coverage
        run: go test -v -covermode=atomic -coverprofile=coverage.out ./...
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          file: ./coverage.out
