name: Lint Golang

on:
  pull_request:
    branches:
      - main

jobs:
  lint-golang:
    uses: crashplangroup/github-workflow-library/.github/workflows/lint-golang.yml@main
    with:
      codecov: true
