name: Lint Markdown

on:
  push:

jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Source Code
        uses: actions/checkout@v2.3.5
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v2
        with:
          files: .
