name: Create Release

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '.github/**'
      - 'docs/**'
  workflow_dispatch:

jobs:
  release:
    runs-on: self-hosted
    steps:
      - name: Check out Source Code
        uses: actions/checkout@v3

      - name: Bump version and push tag
        id: versioner
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.versioner.outputs.new_tag }}
          release_name: Release ${{ steps.versioner.outputs.new_tag }}
          body: ${{ steps.versioner.outputs.changelog }}

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: crashplangroup/axiomatic
          tags: |
            type=raw,value=${{ steps.versioner.outputs.new_tag }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DockerHubUsername }}
          password: ${{ secrets.DockerHubToken }}

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
