name: Twistlock Scan

on:
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '.github/**'
      - 'docs/**'

jobs:
  twistlock:
    uses: crashplangroup/github-workflow-library/.github/workflows/twistlock-scan.yml@main
    with:
      docker_image_name: crashplangroup/axiomatic
    secrets:
      TwistlockURL: ${{ secrets.TWISTLOCKURL }}
      TwistlockUsername: ${{ secrets.TWISTLOCKUSERNAME }}
      TwistlockPassword: ${{ secrets.TWISTLOCKPASSWORD }}
