name: Validate Codeowners

on:
  pull_request:
    paths:
        - '.github/CODEOWNERS'

jobs:
  validate-codeowners:
    uses: crashplangroup/github-workflow-library/.github/workflows/validate-codeowners.yml@main
